# Generated by Django 5.2.4 on 2025-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_farmerprofile_farm_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='buyer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('household', 'Household'), ('company', 'Company')], max_length=20),
        ),
    ]
