# Generated by Django 5.2.4 on 2025-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_buyerprofile_buyer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='buyer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('household', 'Household'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
