# Generated by Django 5.2.4 on 2025-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_buyerprofile_buyer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('household', 'Household'), ('vendor', 'Vendor')], max_length=20, null=True),
        ),
    ]
