# Generated by Django 5.2.5 on 2025-08-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_contact_person_buyerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('household', 'Household'), ('company', 'Company')], max_length=20, null=True),
        ),
    ]
