# Generated by Django 5.2.5 on 2025-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_favorite_product_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
