# Generated by Django 5.2.5 on 2025-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groroulette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinitem',
            name='price_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
