# Generated by Django 5.2.5 on 2025-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groroulette', '0002_spinitem_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
