# Generated by Django 5.2.5 on 2025-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groroulette', '0003_spinitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
