# Generated by Django 5.2.5 on 2025-08-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groroulette', '0005_alter_basket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
