# Generated by Django 5.2.5 on 2025-08-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_buyerprofile_buyer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerprofile',
            old_name='contact_person',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='crops_grown',
            new_name='products',
        ),
    ]
