# Generated by Django 5.2.4 on 2025-08-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='recyclerprofile',
            name='recycling_focus',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='crops_grown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recyclerprofile',
            name='materials_accepted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recyclerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
